"""
EMLP group definition: the 24-element rotation group of the cube
acting on the 24 sticker positions of the 2x2x2 Pocket Cube.

We equivarify against the SPATIAL rotation group O (24 elements),
NOT the cube move group (3.67M states). Two cube states related by
a whole-cube rotation are equally hard to solve — this is the symmetry
we exploit.

Generators:
  x_rot: 90° CW rotation around the R-L axis (viewed from right).
         Equivalent to doing an R move on all layers.
         Face mapping: U->B, B->D, D->F, F->U; R face CW, L face CCW.

  y_rot: 90° CW rotation around the U-D axis (viewed from top).
         Equivalent to doing a U move on all layers.
         Face mapping: F->L, L->B, B->R, R->F; U face CW, D face CCW.

Both generators act on the 24 sticker positions as permutations.
"""

import numpy as np


def _cycles_to_perm(cycles, n=24):
    """Cycle (a,b,c,d) means a->b->c->d->a."""
    perm = list(range(n))
    for cycle in cycles:
        for k in range(len(cycle)):
            perm[cycle[k]] = cycle[(k + 1) % len(cycle)]
    return np.array(perm, dtype=np.int8)


def perm_to_matrix(perm):
    """Convert permutation array to a permutation matrix (float64).

    perm[i]=j means position i goes to j.
    Matrix satisfies: M @ e_i = e_{perm[i]}, i.e., M[perm[i], i] = 1.
    So (M @ v)[perm[i]] = v[i] — sticker values follow their positions.
    """
    n = len(perm)
    M = np.zeros((n, n), dtype=np.float64)
    for i, j in enumerate(perm):
        M[j, i] = 1.0
    return M


# ─── Rotation generator permutations ─────────────────────────────────────────
#
# x_rot (CW from right): applies R-side effect to ALL corners.
#   Right layer (same as R move): (3,12,7,11)(9,1,14,5)(20,21,23,22)
#   Left layer (U->B,F->U,D->F,B->D for UFL,UBL,DBL,DFL):
#     U stickers: (2,13,6,10) — UFL.U->UBL.B->DBL.D->DFL.F (goes B,D,F)
#     F/L/B stickers: (8,0,15,4) — UFL.F->UBL.U->DBL.B->DFL.D
#     L stickers: (17,16,18,19) — L face CCW from left (same axis)
#
# y_rot (CW from top): applies U-side effect to ALL corners.
#   Top layer (same as U move): (0,1,3,2)(9,17,13,21)(8,16,12,20)
#   Bottom layer (F->L,L->B,B->R,R->F for DFL,DFR,DBR,DBL):
#     D stickers: (4,6,7,5) — DFL->DBL->DBR->DFR (D face CCW from top)
#     F/L/B/R stickers: (10,18,14,22)(19,15,23,11)

_X_ROT_CYCLES = [
    # Right layer (R move)
    (3, 12, 7, 11), (9, 1, 14, 5), (20, 21, 23, 22),
    # Left layer
    (2, 13, 6, 10), (8, 0, 15, 4), (17, 16, 18, 19),
]

_Y_ROT_CYCLES = [
    # Top layer (U move)
    (0, 1, 3, 2), (9, 17, 13, 21), (8, 16, 12, 20),
    # Bottom layer
    (4, 6, 7, 5), (10, 18, 14, 22), (19, 15, 23, 11),
]

X_ROT_PERM = _cycles_to_perm(_X_ROT_CYCLES)
Y_ROT_PERM = _cycles_to_perm(_Y_ROT_CYCLES)


# ─── EMLP Group class ─────────────────────────────────────────────────────────

try:
    from emlp.groups import Group as EMLPGroup

    class CubeRotationGroup(EMLPGroup):
        """The 24-element rotation group O of the cube acting on 24 sticker positions.

        Generated by x_rot (90° CW around R-L axis) and y_rot (90° CW around U-D axis).
        The group has exactly 24 elements (verified by enumerate_group_elements()).
        """

        def __init__(self):
            self.discrete_generators = np.stack([
                perm_to_matrix(X_ROT_PERM),
                perm_to_matrix(Y_ROT_PERM),
            ]).astype(np.float64)  # shape (2, 24, 24)
            super().__init__(n=24)

    EMLP_AVAILABLE = True

except ImportError:
    CubeRotationGroup = None
    EMLP_AVAILABLE = False
    print("Warning: emlp not installed. CubeRotationGroup unavailable.")
    print("Install with: pip install emlp")


# ─── Verification ─────────────────────────────────────────────────────────────

def enumerate_group_elements(perm1, perm2, max_elements=200):
    """Enumerate all group elements generated by two permutations via BFS.

    Returns list of permutation arrays.
    """
    identity = np.arange(24, dtype=np.int8)
    generators = [perm1, perm2]
    # Also add inverses
    inv1 = np.empty(24, dtype=np.int8)
    inv1[perm1] = np.arange(24, dtype=np.int8)
    inv2 = np.empty(24, dtype=np.int8)
    inv2[perm2] = np.arange(24, dtype=np.int8)
    generators += [inv1, inv2]

    seen = {tuple(identity.tolist())}
    queue = [identity]
    elements = [identity]

    while queue and len(elements) < max_elements:
        current = queue.pop(0)
        for gen in generators:
            # Compose: apply gen after current
            new_perm = gen[current]
            key = tuple(new_perm.tolist())
            if key not in seen:
                seen.add(key)
                queue.append(new_perm)
                elements.append(new_perm)

    return elements


def verify_rotation_group():
    """Verify that x_rot and y_rot generate exactly 24 group elements."""
    # Verify generators have order 4
    p = X_ROT_PERM.copy()
    for k in range(1, 5):
        if k == 4:
            assert np.all(p == np.arange(24, dtype=np.int8)), \
                f"x_rot does not have order 4 (got order > 4)"
        p = p[X_ROT_PERM]

    p = Y_ROT_PERM.copy()
    for k in range(1, 5):
        if k == 4:
            assert np.all(p == np.arange(24, dtype=np.int8)), \
                f"y_rot does not have order 4"
        p = p[Y_ROT_PERM]

    elements = enumerate_group_elements(X_ROT_PERM, Y_ROT_PERM)
    n = len(elements)
    assert n == 24, f"Expected 24 group elements, got {n}"
    print(f"Rotation group verified: {n} elements ✓")
    return elements


def apply_rotation(perm: np.ndarray, state: np.ndarray) -> np.ndarray:
    """Apply a rotation permutation to a cube state.

    perm[i]=j means sticker at position i goes to position j.
    """
    new_state = np.empty(24, dtype=state.dtype)
    new_state[perm] = state
    return new_state


def get_all_rotations(state: np.ndarray) -> list:
    """Return all 24 rotations of a cube state."""
    elements = enumerate_group_elements(X_ROT_PERM, Y_ROT_PERM)
    return [apply_rotation(elem, state) for elem in elements]


if __name__ == "__main__":
    elements = verify_rotation_group()
    print("x_rot permutation:", X_ROT_PERM)
    print("y_rot permutation:", Y_ROT_PERM)
    print(f"EMLP available: {EMLP_AVAILABLE}")

    if EMLP_AVAILABLE:
        G = CubeRotationGroup()
        print(f"Group created: {G}")
        from emlp.reps import V
        V_rep = V(G)
        print(f"V representation: {V_rep}")
